name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          yarn install

      - name: Build and Deploy
        run: |
          yarn run build
          echo 'mywebsite.com' > build/CNAME
          touch build/.nojekyll
        env:
          REACT_APP_MY_API_KEY: ${{ secrets.MY_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Run weather.js with API Key
        run: |
          cd js
          node weather.js ${{ secrets.MY_API_KEY }}